// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XCHr5bKiF2VRbiJktxne53DceLnoKTU',
    appId: '1:155977803522:web:588203e039d1ff7c98841b',
    messagingSenderId: '155977803522',
    projectId: 'todoapp-ab0cf',
    authDomain: 'todoapp-ab0cf.firebaseapp.com',
    storageBucket: 'todoapp-ab0cf.appspot.com',
    measurementId: 'G-C1SSPSJH9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0taqJXgh0pfw15JpJzi_ibiMb8DNIqnM',
    appId: '1:155977803522:android:522021d33331223398841b',
    messagingSenderId: '155977803522',
    projectId: 'todoapp-ab0cf',
    storageBucket: 'todoapp-ab0cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJkfuEAhdiIRb40e-I4mfEtLEKXPr1YQ',
    appId: '1:155977803522:ios:27eccc32f88aadfc98841b',
    messagingSenderId: '155977803522',
    projectId: 'todoapp-ab0cf',
    storageBucket: 'todoapp-ab0cf.appspot.com',
    iosBundleId: 'com.example.signinwithTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJkfuEAhdiIRb40e-I4mfEtLEKXPr1YQ',
    appId: '1:155977803522:ios:27eccc32f88aadfc98841b',
    messagingSenderId: '155977803522',
    projectId: 'todoapp-ab0cf',
    storageBucket: 'todoapp-ab0cf.appspot.com',
    iosBundleId: 'com.example.signinwithTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-XCHr5bKiF2VRbiJktxne53DceLnoKTU',
    appId: '1:155977803522:web:5d6be045a20e0a8b98841b',
    messagingSenderId: '155977803522',
    projectId: 'todoapp-ab0cf',
    authDomain: 'todoapp-ab0cf.firebaseapp.com',
    storageBucket: 'todoapp-ab0cf.appspot.com',
    measurementId: 'G-TVHYQ1DL4L',
  );
}
